version: "3.2"

services:
    nginx:
        build:
            context: .
            dockerfile: docker/Nginx.Dockerfile
        ports:
            - 8090:80
        links:
            - fpm
        volumes:
          - ./:/var/www/laravel-docker
    fpm:
        build:
            context: .
            dockerfile: docker/Fpm.Dockerfile
        volumes:
            - ./:/var/www/laravel-docker
        links:
            - pgsql
    pgsql:
        image: postgres
        restart: always
        ports:
            - 5433:5432
        environment:
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=laravel
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080